import { chromium } from 'playwright'; import http from 'node:http'; import fs from 'node:fs';
const out = process.argv[2], html = process.argv[3] || 'dist/web/index.html', tag = process.argv[4] || 'before';
const srv = http.createServer((q, r) => { r.writeHead(200, { 'content-type': 'text/html' }); r.end(fs.readFileSync(html)); }).listen(8796);
const b = await chromium.launch(); const ctx = await b.newContext({ viewport: { width: 1280, height: 720 } });
await ctx.route(/googleapis/, r => r.fulfill({ status: 200, contentType: 'text/css', body: "/* latin */ @font-face { font-family: 'Lilita One'; src: url(https://fonts.gstatic.com/l.ttf); }" }));
await ctx.route(/gstatic\.com\/l\.ttf/, r => r.fulfill({ status: 200, contentType: 'font/ttf', body: fs.readFileSync(process.env.FONT) }));
await ctx.route(/firebasejs/, r => r.abort());
const p = await ctx.newPage(); const errs = []; p.on('pageerror', e => errs.push(e.message));
await p.goto('http://127.0.0.1:8796/'); await p.waitForFunction(() => typeof Game !== 'undefined' && Game.screen === 'title', null, { timeout: 30000 }); await p.waitForTimeout(800);
const shot = async (name, fn, wait = 700) => { if (fn) await p.evaluate(fn); await p.waitForTimeout(wait); await p.screenshot({ path: `${out}/${tag}-${name}.png` }); };
await shot('cmenu-fresh', () => { Game.screen = 'cmenu'; Game.idx = 0; });
await shot('cmenu-save', () => { C = freshCareer(); C.name = 'Hemza'; C.bracket = makeBracket(0); saveCareer(); Game.screen = 'cmenu'; Game.idx = 0; });
await shot('creator', () => { C = freshCareer(); Game.creator = { idx: 2, isNew: true }; setupPractice('free'); Game.screen = 'creator'; }, 1200);
await shot('story-1', () => { C.name = 'Hemza'; creatorDone(); }, 1500);
for (let i = 2; i <= 5; i++) await shot('story-' + i, () => { Input.pressed.Enter = true; }, 900);
console.log('screens:', await p.evaluate(() => Game.screen), 'story lines:', await p.evaluate(() => Game.story ? Game.story.lines.length : null), 'errors:', errs);
await b.close(); srv.close();
